"use client";
import { useState, type CSSProperties } from "react";

const palettes = [
  { name: ["Royal Navy", "كحلي ملكي"], colours: ["#07111F", "#D6B15F", "#5FA8FF", "#F5F7FA"], note: ["Formal, confident and established.", "حضور رسمي وواثق وراسخ."] },
  { name: ["Industrial", "صناعي"], colours: ["#071B28", "#C5DF31", "#13C4E2", "#F4F8FA"], note: ["Energetic, operational and easy to recognise.", "حيوية وطابع تشغيلي وسهولة تمييز."] },
  { name: ["Emerald", "زمردي"], colours: ["#102D28", "#C9A55A", "#8FC9B6", "#F5F8F6"], note: ["Calm, refined and relationship-focused.", "هدوء ورقي وحضور يعكس الثقة."] },
];
const fontPairs = [
  { name: ["Modern & clear", "حديث وواضح"], en: '"DM Sans", Arial, sans-serif', ar: '"Cairo", Arial, sans-serif', names: "DM Sans + Cairo" },
  { name: ["Editorial & formal", "تحريري ورسمي"], en: 'Georgia, serif', ar: '"Noto Serif Arabic", serif', names: "Georgia + Noto Serif Arabic" },
  { name: ["Practical & direct", "عملي ومباشر"], en: 'Arial, sans-serif', ar: 'Tahoma, Arial, sans-serif', names: "Arial + Tahoma" },
];
export default function BrandWorkshop({ ar }: { ar: boolean }) {
  const [palette, setPalette] = useState(0);
  const [font, setFont] = useState(0);
  const [logo, setLogo] = useState(0);
  const t = (en: string, arabic: string) => ar ? arabic : en;
  const p = palettes[palette];
  const names = [t("01 / Existing SAC symbol", "01 / رمز SAC الحالي"), t("02 / Geometric wordmark", "02 / شعار كتابي هندسي"), t("03 / Editorial wordmark", "03 / شعار كتابي رسمي")];
  const style = { "--brand-base": p.colours[0], "--brand-accent": p.colours[1], "--brand-secondary": p.colours[2], "--brand-paper": p.colours[3] } as CSSProperties;
  return <div className="gc-brand-lab" style={style}>
    <div className="gc-lab-heading"><p className="gc-kicker">{t("TRY THE DESIGN DECISIONS", "جرّب قرارات التصميم")}</p><h3>{t("Colours. Type. Logo.", "ألوان. خطوط. شعار.")}</h3><p>{t("Change each element and see the result immediately. During your project, we compare directions against your audience, sector and real uses, then record your approved choices.", "غيّر العناصر وشاهد النتيجة مباشرة. في مشروعك نقارن التوجهات بحسب جمهورك وقطاعك واستخداماتك الفعلية، ثم نوثّق اختياراتك المعتمدة.")}</p></div>
    <div className="gc-lab-grid"><div className="gc-lab-controls">
      <fieldset><legend>{t("1. Choose the colour direction", "1. اختر التوجه اللوني")}</legend><div className="gc-palette-buttons">{palettes.map((item, i) => <button key={item.name[0]} aria-pressed={palette === i} onClick={() => setPalette(i)}><span className="gc-mini-swatches" aria-hidden="true">{item.colours.map(c => <i key={c} style={{ background: c }} />)}</span><span>{item.name[ar ? 1 : 0]}</span></button>)}</div><p>{p.note[ar ? 1 : 0]} {t("We check contrast, small-size legibility and light/dark applications before approval.", "نراجع التباين والوضوح بالأحجام الصغيرة وعلى الخلفيات الفاتحة والغامقة قبل الاعتماد.")}</p></fieldset>
      <fieldset><legend>{t("2. Compare Arabic & English type", "2. قارن الخط العربي والإنجليزي")}</legend><div className="gc-font-buttons">{fontPairs.map((pair,i) => <button key={pair.names} aria-pressed={font === i} onClick={() => setFont(i)}><b>{pair.name[ar ? 1 : 0]}</b><span dir="ltr">{pair.names}</span></button>)}</div><p>{t("We agree heading and body fonts, weights and spacing, then check Arabic and English together. Font licensing is confirmed for the intended use.", "نتفق على خطوط العناوين والنصوص وأوزانها ومسافاتها، ونراجع العربية والإنجليزية معاً، ونتأكد من الترخيص للاستخدام المطلوب.")}</p></fieldset>
    </div><div className="gc-brand-preview" aria-live="polite"><div className="gc-preview-brandline" dir="ltr"><span>SAC / BRAND PREVIEW</span><span>0{palette + 1}</span></div><div className={`gc-live-wordmark gc-live-wordmark-${logo}`} dir="ltr">{logo === 0 && <img src="https://yassernet1990.github.io/sac-cards/assets/sac-logo.svg" width="82" height="64" alt="" />}<div><strong>SAC{logo === 1 && <span>.</span>}</strong><small>LOGISTICS</small></div></div><div className="gc-type-specimen"><h4 style={{fontFamily:fontPairs[font].ar}} lang="ar" dir="rtl">نحرّك أعمالك إلى الأمام.</h4><h4 style={{fontFamily:fontPairs[font].en}} lang="en" dir="ltr">Moving your business forward.</h4><p style={{fontFamily:fontPairs[font].ar}} lang="ar" dir="rtl">حلول المعدات والنقل والدعم التشغيلي.</p><p style={{fontFamily:fontPairs[font].en}} lang="en" dir="ltr">Equipment, transport and operational support.</p></div><div className="gc-colour-tokens">{p.colours.map((c,i) => <div key={c}><i style={{background:c}} /><code>{c}</code><span>{[t("Base", "أساسي"),t("Accent", "إبراز"),t("Secondary", "مساند"),t("Background", "خلفية")][i]}</span></div>)}</div></div></div>
    <fieldset className="gc-logo-field"><legend>{t("3. Compare different logo approaches", "3. قارن أساليب مختلفة للشعار")}</legend><div className="gc-logo-options">{names.map((name,i) => <button key={name} className={`gc-logo-option gc-logo-option-${i}`} aria-pressed={logo===i} onClick={()=>setLogo(i)}><span className="gc-logo-sample" dir="ltr">{i===0 && <img src="https://yassernet1990.github.io/sac-cards/assets/sac-logo.svg" width="64" height="49" alt="" />}<span><strong>SAC{i===1&&<i>.</i>}</strong><small>LOGISTICS</small></span></span><b>{name}</b><span>{logo===i?t("In the preview ✓", "ظاهر في المعاينة ✓"):t("Preview this approach", "عاين هذا الأسلوب")}</span></button>)}</div></fieldset>
    <p className="gc-note">{t("The first option uses the existing SAC symbol; the other two are illustrative wordmark studies, not final commissioned logos. These local choices are not saved or sent. The SAC symbol retains its original colours; the selected palette updates the surrounding identity.", "الخيار الأول يستخدم رمز SAC الحالي؛ والآخران دراستان توضيحيتان لشعار كتابي، وليسا شعارات نهائية معتمدة. الاختيارات هنا محلية ولا تُحفظ أو تُرسل. يحتفظ رمز SAC بألوانه الأصلية وتتغيّر الهوية المحيطة وفق اللوحة المختارة.")}</p>
  </div>;
}

export function VisualTimeline({ ar, rows }: { ar: boolean; rows: string[][] }) {
  return <div className="gc-timeline"><div className="gc-timeline-heading"><h3>{ar ? "رحلتك على خط زمني واحد." : "Your journey on one timeline."}</h3><p>{ar ? "كل مربع = يوم عمل. اقرأ مدد العمل والاختيار من اليسار إلى اليمين." : "Each column is one working day. Read the work and review windows from left to right."}</p><div className="gc-timeline-legend"><span><i className="masar" />{ar?"مسار":"MASAR"}</span><span><i className="client" />{ar?"العميل":"Client"}</span><span><i className="joint" />{ar?"اعتماد مشترك":"Joint approval"}</span></div></div><div className="gc-timeline-scroll" role="region" aria-label={ar?"شريط البرنامج الزمني؛ قابل للتمرير أفقياً":"Project timeline; scroll horizontally"} tabIndex={0}><div className="gc-gantt" dir="ltr"><div className="gc-gantt-axis"><span>{ar?"المرحلة / اليوم":"STAGE / DAY"}</span><div>{Array.from({length:22},(_,i)=><b key={i}>{i+1}</b>)}</div></div>{rows.map((row,i)=>{const [start,end] = row[0].split("–").map(Number);const duration=(end||start)-start+1;const owner=[2,5,8].includes(i)?"client":[0,3,11].includes(i)?"joint":"masar";return <div className="gc-gantt-row" key={row[0]}><span dir={ar?"rtl":"ltr"}>{row[ar?2:1]}</span><div className="gc-gantt-track"><span className={`gc-gantt-bar ${owner}`} style={{gridColumn:`${start} / span ${duration}`}} title={`${row[0]} · ${row[ar?2:1]}`}><b>{duration>1?row[0]:"◆"}</b></span></div></div>})}</div></div><p className="gc-note">{ar?"خطة مقترحة: تتغير المواعيد التابعة إذا تأخر المحتوى أو الاعتماد. التفاصيل والمسؤوليات في الجدول أدناه.":"Proposed plan: dependent dates move if content or approval is delayed. Detailed responsibilities follow below."}</p></div>;
}
