"use client";
import { useState, type CSSProperties } from "react";

const palettes = [
  { name: ["Navy & gold", "كحلي وذهبي"], colours: ["#091B34", "#E9BB63", "#91C9FF", "#F5F8FF"], note: ["A formal, premium corporate direction.", "توجه مؤسسي رسمي وفاخر."] },
  { name: ["Ivory & terracotta", "عاجي وطوبي"], colours: ["#FFF2DE", "#A83912", "#914600", "#52200D"], note: ["A bright, warm identity with earthy accents.", "هوية فاتحة ودافئة بلمسات ترابية."] },
  { name: ["Violet & electric", "بنفسجي وكهربائي"], colours: ["#3B0764", "#F0ABFC", "#67E8F9", "#FAF5FF"], note: ["An expressive, energetic digital direction.", "توجه رقمي جريء ومفعم بالحيوية."] },
  { name: ["Emerald & lime", "زمردي وليموني"], colours: ["#065F46", "#FDE047", "#6EE7B7", "#ECFDF5"], note: ["A fresh green identity with vivid yellow accents.", "هوية خضراء منعشة بلمسات صفراء واضحة."] },
];
function SacMark() { return <svg className="gc-sac-mark" viewBox="0 0 420 320" width="82" height="64" aria-hidden="true"><path fill="var(--brand-accent)" d="M24 103 132 12h264l-75 58H158l-33 31 119 27-71 61z"/><path fill="var(--brand-secondary)" d="m296 126 82 18-194 164-41-45z"/></svg>; }
const fontPairs = [
  { name: ["Modern & clear", "حديث وواضح"], en: '"DM Sans", Arial, sans-serif', ar: '"Cairo", Arial, sans-serif', names: "DM Sans + Cairo" },
  { name: ["Editorial & formal", "تحريري ورسمي"], en: 'Georgia, serif', ar: '"Noto Serif Arabic", serif', names: "Georgia + Noto Serif Arabic" },
  { name: ["Practical & direct", "عملي ومباشر"], en: 'Arial, sans-serif', ar: 'Tahoma, Arial, sans-serif', names: "Arial + Tahoma" },
];
export default function BrandWorkshop({ ar }: { ar: boolean }) {
  const [palette, setPalette] = useState(0);
  const [font, setFont] = useState(0);
  const [logo, setLogo] = useState(0);
  const t = (en: string, arabic: string) => ar ? arabic : en;
  const p = palettes[palette];
  const names = [t("01 / Existing SAC symbol", "01 / رمز SAC الحالي"), t("02 / Geometric wordmark", "02 / شعار كتابي هندسي"), t("03 / Editorial wordmark", "03 / شعار كتابي رسمي")];
  const style = { "--brand-base": p.colours[0], "--brand-accent": p.colours[1], "--brand-secondary": p.colours[2], "--brand-paper": p.colours[3], "--brand-font-ar": fontPairs[font].ar, "--brand-font-en": fontPairs[font].en } as CSSProperties;
  return <div className="gc-brand-lab" style={style}>
    <div className="gc-lab-heading"><p className="gc-kicker">{t("TRY THE DESIGN DECISIONS", "جرّب قرارات التصميم")}</p><h3>{t("Colours. Type. Logo.", "ألوان. خطوط. شعار.")}</h3><p>{t("Change each element and see the result immediately. During your project, we compare directions against your audience, sector and real uses, then record your approved choices.", "غيّر العناصر وشاهد النتيجة مباشرة. في مشروعك نقارن التوجهات بحسب جمهورك وقطاعك واستخداماتك الفعلية، ثم نوثّق اختياراتك المعتمدة.")}</p></div>
    <div className="gc-lab-grid"><div className="gc-lab-controls">
      <fieldset><legend>{t("1. Choose the colour direction", "1. اختر التوجه اللوني")}</legend><div className="gc-palette-buttons">{palettes.map((item, i) => <button key={item.name[0]} aria-pressed={palette === i} onClick={() => setPalette(i)}><span className="gc-mini-swatches" aria-hidden="true">{item.colours.map(c => <i key={c} style={{ background: c }} />)}</span><span>{item.name[ar ? 1 : 0]}</span></button>)}</div><p>{p.note[ar ? 1 : 0]} {t("We check contrast, small-size legibility and light/dark applications before approval.", "نراجع التباين والوضوح بالأحجام الصغيرة وعلى الخلفيات الفاتحة والغامقة قبل الاعتماد.")}</p></fieldset>
      <fieldset><legend>{t("2. Compare Arabic & English type", "2. قارن الخط العربي والإنجليزي")}</legend><div className="gc-font-buttons">{fontPairs.map((pair,i) => <button key={pair.names} aria-pressed={font === i} onClick={() => setFont(i)}><b>{pair.name[ar ? 1 : 0]}</b><span dir="ltr">{pair.names}</span></button>)}</div><p>{t("We agree heading and body fonts, weights and spacing, then check Arabic and English together. Font licensing is confirmed for the intended use.", "نتفق على خطوط العناوين والنصوص وأوزانها ومسافاتها، ونراجع العربية والإنجليزية معاً، ونتأكد من الترخيص للاستخدام المطلوب.")}</p></fieldset>
    </div><div className="gc-brand-preview" aria-live="polite"><div className="gc-preview-choice">{p.name[ar ? 1 : 0]} · <span dir="ltr">{fontPairs[font].names}</span></div><div className="gc-preview-brandline" dir="ltr"><span>SAC / BRAND PREVIEW</span><span>0{palette + 1}</span></div><div className={`gc-live-wordmark gc-live-wordmark-${logo}`} dir="ltr">{logo === 0 && <SacMark />}<div><strong>SAC{logo === 1 && <span>.</span>}</strong><small>LOGISTICS</small></div></div><div className="gc-type-specimen"><h4 style={{fontFamily:fontPairs[font].ar}} lang="ar" dir="rtl">نحرّك أعمالك إلى الأمام.</h4><h4 style={{fontFamily:fontPairs[font].en}} lang="en" dir="ltr">Moving your business forward.</h4><p style={{fontFamily:fontPairs[font].ar}} lang="ar" dir="rtl">حلول المعدات والنقل والدعم التشغيلي.</p><p style={{fontFamily:fontPairs[font].en}} lang="en" dir="ltr">Equipment, transport and operational support.</p></div><div className="gc-colour-tokens">{p.colours.map((c,i) => <div key={c}><i style={{background:c}} /><code>{c}</code><span>{[t("Base", "أساسي"),t("Accent", "إبراز"),t("Secondary", "مساند"),t("Text", "نصوص")][i]}</span></div>)}</div></div></div>
    <fieldset className="gc-logo-field"><legend>{t("3. Compare different logo approaches", "3. قارن أساليب مختلفة للشعار")}</legend><div className="gc-logo-options">{names.map((name,i) => <button key={name} className={`gc-logo-option gc-logo-option-${i}`} aria-pressed={logo===i} onClick={()=>setLogo(i)}><span className="gc-logo-sample" dir="ltr">{i===0 && <SacMark />}<span><strong>SAC{i===1&&<i>.</i>}</strong><small>LOGISTICS</small></span></span><b>{name}</b><span>{logo===i?t("In the preview ✓", "ظاهر في المعاينة ✓"):t("Preview this approach", "عاين هذا الأسلوب")}</span></button>)}</div></fieldset>
    <p className="gc-note">{t("The first option uses the existing SAC symbol; the other two are illustrative wordmark studies, not final commissioned logos. These local choices are not saved or sent. The selected palette updates the symbol and its applications; the selected fonts update the Arabic and English preview.", "الخيار الأول يستخدم رمز SAC الحالي؛ والآخران دراستان توضيحيتان لشعار كتابي، وليسا شعارات نهائية معتمدة. الاختيارات هنا محلية ولا تُحفظ أو تُرسل. تُطبّق الألوان المختارة على الرمز وتطبيقاته، والخطوط على المعاينة العربية والإنجليزية.")}</p>
  </div>;
}

export function VisualTimeline({ ar, rows }: { ar: boolean; rows: string[][] }) {
  return <div className="gc-timeline"><div className="gc-timeline-heading"><h3>{ar ? "رحلتك على خط زمني واحد." : "Your journey on one timeline."}</h3><p>{ar ? "كل مربع = يوم عمل. اقرأ مدد العمل والاختيار من اليسار إلى اليمين." : "Each column is one working day. Read the work and review windows from left to right."}</p><div className="gc-timeline-legend"><span><i className="masar" />{ar?"مسار":"MASAR"}</span><span><i className="client" />{ar?"العميل":"Client"}</span><span><i className="joint" />{ar?"اعتماد مشترك":"Joint approval"}</span></div></div><div className="gc-timeline-scroll" role="region" aria-label={ar?"شريط البرنامج الزمني؛ قابل للتمرير أفقياً":"Project timeline; scroll horizontally"} tabIndex={0}><div className="gc-gantt" dir="ltr"><div className="gc-gantt-axis"><span>{ar?"المرحلة / اليوم":"STAGE / DAY"}</span><div>{Array.from({length:22},(_,i)=><b key={i}>{i+1}</b>)}</div></div>{rows.map((row,i)=>{const [start,end] = row[0].split("–").map(Number);const duration=(end||start)-start+1;const owner=[2,5,8].includes(i)?"client":[0,3,11].includes(i)?"joint":"masar";return <div className="gc-gantt-row" key={row[0]}><span dir={ar?"rtl":"ltr"}>{row[ar?2:1]}</span><div className="gc-gantt-track"><span className={`gc-gantt-bar ${owner}`} style={{gridColumn:`${start} / span ${duration}`}} title={`${row[0]} · ${row[ar?2:1]}`}><b>{duration>1?row[0]:"◆"}</b></span></div></div>})}</div></div><p className="gc-note">{ar?"خطة مقترحة: تتغير المواعيد التابعة إذا تأخر المحتوى أو الاعتماد. التفاصيل والمسؤوليات في الجدول أدناه.":"Proposed plan: dependent dates move if content or approval is delayed. Detailed responsibilities follow below."}</p></div>;
}
