"use client";
import { useEffect, useState } from "react";
import BrandWorkshop, { VisualTimeline } from "./brand-workshop";

const links = ["https://yassernet1990.github.io/sac-cards/", "https://yassernet1990.github.io/sac-cards2/", "https://yassernet1990.github.io/sac-cards3/#royalnavy", "https://yassernet1990.github.io/sac1/", "https://yassernet1990.github.io/sac2/", "https://yassernet1990.github.io/sac3/site.html"];
const steps = [
  ["1", "Kickoff & brief", "الانطلاق وفهم الشركة", "Confirm scope, pages, languages and one decision-maker.", "تأكيد النطاق والصفحات واللغات ومسؤول الاعتماد."],
  ["2–3", "Brand concepts", "إعداد أفكار الهوية", "MASAR prepares 3 logo concepts with colours and applications.", "مسار تجهّز 3 أفكار للشعار مع الألوان والتطبيقات."],
  ["4–5", "Your brand selection", "اختيارك للهوية", "Choose one direction and send consolidated feedback in 2 days.", "اختر توجهاً واحداً وأرسل ملاحظاتك مجمّعة خلال يومين."],
  ["6", "Identity approval", "اعتماد الهوية", "Refine and approve the logo, palette and typography.", "تنقيح واعتماد الشعار ولوحة الألوان والخطوط."],
  ["7–8", "Website concepts", "نماذج الموقع", "MASAR presents 3 initial website directions using your identity.", "مسار تعرض 3 توجهات مبدئية للموقع بهويتك المعتمدة."],
  ["9–11", "Your selection & content", "اختيارك ومحتوى الموقع", "Choose one concept and supply all website content within 3 days.", "اختر نموذجاً واحداً وسلّم محتوى الموقع كاملاً خلال 3 أيام."],
  ["12–14", "Website production", "تنفيذ الموقع", "3 working days after the design and complete content are approved.", "3 أيام عمل بعد اعتماد التصميم واستلام المحتوى كاملاً."],
  ["15", "Profile directions", "توجهات البروفايل", "MASAR presents alternative layouts in the approved identity.", "مسار تعرض أكثر من توجه لتصميم البروفايل بالهوية المعتمدة."],
  ["16–17", "Your profile data", "بيانات البروفايل واعتمادك", "Choose the layout and send verified profile data within 2 days.", "اختيار تصميم البروفايل وإرسال البيانات المدققة خلال يومين."],
  ["18–19", "Profile & website alignment", "تنفيذ البروفايل وتحديث الموقع", "Produce 10–12 pages, then align approved information on the website.", "إنتاج 10–12 صفحة وتوحيد المعلومات المعتمدة على الموقع."],
  ["20–21", "Remaining deliverables", "استكمال بقية المخرجات", "Prepare branded documents, email and LinkedIn assets.", "تجهيز المستندات والبريد ومواد لينكدإن بالهوية المعتمدة."],
  ["22", "Final review & launch", "المراجعة والإطلاق والتسليم", "Client sign-off, launch and organised handover.", "الاعتماد النهائي من العميل والإطلاق وتسليم الملفات منظّمة."],
];

const Block = ({label, text}: {label:string; text:string}) => <div><h3>{label}</h3><p>{text}</p></div>;

export default function GrowJourney({ ar }: { ar: boolean }) {
  const t = (en: string, arabic: string) => ar ? arabic : en;
  const ids = ["overview", "identity", "website", "profile", "handover", "schedule"];
  const labels = ar ? ["الرحلة", "الهوية", "الموقع", "البروفايل", "التسليم", "الجدول"] : ["Journey", "Identity", "Website", "Profile", "Handover", "Timeline"];
  const [active, setActive] = useState(0);
  const [copied, setCopied] = useState(false);
  useEffect(() => {
    const nodes = ids.map(id => document.getElementById(id));
    let frame = 0;
    const update = () => { frame = 0; let next = 0; nodes.forEach((node,i) => { if(node && node.getBoundingClientRect().top < innerHeight * .4) next = i; }); setActive(next); };
    const onScroll = () => { if(!frame) frame = requestAnimationFrame(update); };
    update(); window.addEventListener("scroll", onScroll, {passive:true});
    return () => { window.removeEventListener("scroll", onScroll); cancelAnimationFrame(frame); };
  // IDs are fixed across the two languages.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    const nodes = document.querySelectorAll(".gc-section-title, .gc-gallery article, .gc-brand-lab, .gc-timeline, .gc-handover-grid article");
    const observer = new IntersectionObserver(entries => {
      entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("gc-revealed"); observer.unobserve(entry.target); } });
    }, { threshold: .08 });
    nodes.forEach(node => { if (node.getBoundingClientRect().top > window.innerHeight) { node.classList.add("gc-reveal"); observer.observe(node); } });
    return () => { observer.disconnect(); nodes.forEach(node => node.classList.remove("gc-reveal", "gc-revealed")); };
  }, []);
  const gate = (text:string) => <div className="gc-gate"><span>✓</span><p>{text}</p></div>;
  const gallery = (brand:boolean) => {
    const names = brand ? [t("01 / Industrial identity", "01 / الهوية الصناعية"),t("02 / Signature collection", "02 / المجموعة المميزة"),t("03 / Royal Navy collection", "03 / مجموعة Royal Navy")] : [t("01 / Immersive & dynamic", "01 / عرض بصري وحركة"),t("02 / Structured & corporate", "02 / تنظيم مؤسسي واضح"),t("03 / Bold & operational", "03 / حضور قوي ومباشر")];
    const descriptions = brand ? [t("10 visual themes, with applications that help you compare the complete identity.", "10 توجهات لونية مع تطبيقات تساعدك على مقارنة الهوية المتكاملة."),t("10 themes, including Jeddah Heritage, Royal Navy and Corporate Blue.", "10 توجهات، منها تراث جدة وRoyal Navy والأزرق المؤسسي."),t("16 themes; the link opens Royal Navy with navy, gold and bright blue.", "16 توجهاً؛ يفتح الرابط Royal Navy بالكحلي والذهبي والأزرق.")] : [t("A visual opening, service cards and a step-by-step operations journey.", "افتتاحية بصرية وبطاقات خدمات وتسلسل يشرح رحلة التشغيل."),t("A corporate presentation with clear service hierarchy and equipment information.", "عرض مؤسسي بتقسيم واضح للخدمات ومعلومات المعدات."),t("Large headlines, industrial imagery and prominent calls to action.", "عناوين كبيرة وصور صناعية وأزرار تواصل بارزة.")];
    return <div className="gc-gallery">{names.map((name,i) => <article key={name}><a className="gc-preview" href={links[i+(brand?0:3)]} target="_blank" rel="noopener noreferrer" aria-label={name}><div className="gc-browser-bar"><span>● ● ●</span><span>{brand ? "IDENTITY EXPLORER" : "WEBSITE CONCEPT"} / 0{i+1}</span><span>↗</span></div><img src={`/images/grow-case/preview-${i+(brand?1:4)}.webp`} width="1360" height="940" alt={name} loading="lazy" /></a><div className="gc-gallery-copy"><h3>{name}</h3><p>{descriptions[i]}</p><a className="gc-text-link" href={links[i+(brand?0:3)]} target="_blank" rel="noopener noreferrer">{t("Explore live example", "افتح النموذج التفاعلي")} ↗</a></div></article>)}</div>;
  };
  const checklist = (items:string[]) => <ul className="gc-checklist">{items.map(item=><li key={item}><span>✓</span>{item}</li>)}</ul>;
  const requestText = t("GROW — project content\nCompany name (Arabic / English):\nBusiness activity and target audience:\nApproved website concept:\nAbout the company:\nServices and descriptions:\nProjects / experience / approved client names:\nContact details, address and social links:\nRequired pages and languages:\nLinks to approved images and logo files:\nProfile-specific facts, team and credentials:\nDecision-maker:","GROW — محتوى المشروع\nاسم الشركة بالعربية والإنجليزية:\nالنشاط والجمهور المستهدف:\nنموذج الموقع المعتمد:\nنبذة عن الشركة:\nالخدمات ووصف كل خدمة:\nالمشاريع والخبرات وأسماء العملاء المسموح بنشرها:\nبيانات التواصل والعنوان وروابط الحسابات:\nالصفحات واللغات المطلوبة:\nروابط الصور وملفات الشعار المعتمدة:\nبيانات البروفايل والفريق والمؤهلات:\nمسؤول الاعتماد:");
  return <>
    <nav className="gc-rail" aria-label={t("Journey sections", "مراحل الرحلة")}><span className="gc-rail-line"><i style={{transform:`scaleY(${active / 5})`}} /></span>{ids.map((id,i)=><a href={`#${id}`} key={id} aria-label={labels[i]} aria-current={active === i ? "location" : undefined}>{String(i+1).padStart(2,"0")}</a>)}<span className="gc-rail-label">{labels[active]}</span></nav>
    <div className="gc-stage-strip">{ids.slice(1).map((id,i)=><a key={id} href={`#${id}`}><b>0{i+1}</b>{labels[i+1]}<span>↗</span></a>)}</div>
    <section className="gc-section gc-light" id="identity"><div className="gc-wrap"><p className="gc-kicker">01 / {t("IDENTITY FIRST · DAYS 1–6", "الهوية أولاً · الأيام 1–6")}</p><div className="gc-section-title"><h2>{t("See your brand.", "شاهد هويتك.")}<br /><em>{t("Before you choose it.", "قبل أن تختارها.")}</em></h2><p>{t("We begin with your company story and prepare 3 logo concepts. Colours, typography and realistic applications help you judge how each direction works beyond the logo itself.", "نبدأ بفهم قصة شركتك ونجهز 3 أفكار للشعار. نعرض معها الألوان والخطوط وتطبيقات بصرية تساعدك على تقييم كل توجه في الاستخدام الفعلي.")}</p></div>
    <div className="gc-io"><Block label={t("You provide", "المدخلات منك")} text={t("Company name in both languages, activity, audience, positioning, preferred references and any existing identity files.", "اسم الشركة باللغتين، النشاط، الجمهور، التوجه المطلوب، أمثلة تعجبك وأي ملفات هوية سابقة.")} /><Block label={t("MASAR delivers", "المخرجات من مسار")} text={t("3 initial logo concepts, proposed palettes and typography, plus sample identity applications for comparison.", "3 أفكار مبدئية للشعار، لوحات ألوان وخطوط مقترحة، وأمثلة لتطبيق الهوية للمقارنة.")} /><Block label={t("Your decision · 2 working days", "قرارك · يومان عمل")} text={t("Choose one direction and send one consolidated feedback list. Confirm the final logo, colours and fonts before website design starts.", "اختر توجهاً واحداً وأرسل ملاحظاتك في قائمة موحّدة. اعتمد الشعار النهائي والألوان والخطوط قبل بدء تصميم الموقع.")} /></div>
    <BrandWorkshop ar={ar} />{gallery(true)}<p className="gc-note">{t("These galleries illustrate how to compare identities; the number of gallery themes is not the number of custom logo concepts included. Vehicle and merchandise mockups demonstrate the identity, with production outside Grow’s scope.", "هذه المعارض تشرح طريقة مقارنة الهويات؛ عدد توجهاتها لا يعبّر عن عدد أفكار الشعارات المخصصة في الباقة. صور المركبات والمنتجات تطبيقات توضيحية للهوية، وتصنيعها خارج نطاق Grow.")}</p>
    {gate(t("APPROVAL 01 — One logo. One colour palette. One typography system. We record your written approval and carry the same identity into every deliverable.", "الاعتماد 01 — شعار واحد، لوحة ألوان واحدة، ونظام خطوط موحّد. نوثّق اعتمادك الكتابي ونطبّق الهوية نفسها على جميع المخرجات."))}</div></section>
    <section className="gc-section gc-dark" id="website"><div className="gc-wrap"><p className="gc-kicker">02 / {t("WEBSITE · DAYS 7–14", "الموقع · الأيام 7–14")}</p><div className="gc-section-title"><h2>{t("Three directions.", "ثلاثة توجهات.")}<br /><em>{t("One website for you.", "موقع واحد يعكسك.")}</em></h2><p>{t("After identity approval, we prepare three initial website directions. Compare the page structure, first impression and way your services are presented—then choose the direction we will develop.", "بعد اعتماد الهوية نصمم ثلاثة توجهات أولية للموقع. قارن ترتيب الصفحة والانطباع الأول وطريقة عرض الخدمات، ثم اختر التوجه الذي سنطوّره.")}</p></div>{gallery(false)}
    <div className="gc-three-days"><div><strong>3</strong><h3>{t("days for your content", "أيام لتسليم محتواك")}</h3><p>{t("Days 9–11: choose one concept and provide the complete, approved website content.", "الأيام 9–11: اختر نموذجاً واحداً وقدّم محتوى الموقع كاملاً ومعتمداً.")}</p></div><span aria-hidden="true">+</span><div><strong>3</strong><h3>{t("days to build your website", "أيام لتنفيذ موقعك")}</h3><p>{t("Days 12–14: we build after both the concept and complete content are confirmed. Final launch follows profile alignment and sign-off.", "الأيام 12–14: نبدأ التنفيذ بعد اعتماد النموذج واستلام المحتوى كاملاً. يأتي الإطلاق النهائي بعد مواءمة البروفايل والاعتماد.")}</p></div></div>
    <div className="gc-io"><Block label={t("Content you send", "المحتوى المطلوب منك")} text={t("Company introduction, services, project references, approved images, contact details and final text in the agreed languages.", "نبذة الشركة، الخدمات، المشاريع المرجعية، الصور المعتمدة، بيانات التواصل والنصوص النهائية باللغات المتفق عليها.")} /><Block label={t("What we build", "ما ننفّذه لك")} text={t("The agreed corporate website, responsive layouts, approved content, working navigation and basic SEO.", "موقع الشركة بالصفحات المتفق عليها، تصميم متجاوب، المحتوى المعتمد، روابط فعالة وتهيئة أساسية لمحركات البحث.")} /><Block label={t("What you approve", "ما تعتمده")} text={t("One design direction, page structure and content. The three concepts are selection options for one final website.", "توجهاً تصميمياً واحداً وهيكل الصفحات ومحتواها. النماذج الثلاثة خيارات للاختيار منها لتنفيذ موقع نهائي واحد.")} /></div>{gate(t("APPROVAL 02 — Website direction + complete content. The 3-day production window starts only after both are ready.", "الاعتماد 02 — توجه الموقع + المحتوى الكامل. تبدأ مدة التنفيذ البالغة 3 أيام بعد اكتمالهما معاً."))}</div></section>
    <section className="gc-section gc-light" id="profile"><div className="gc-wrap"><p className="gc-kicker">03 / {t("COMPANY PROFILE · DAYS 15–19", "بروفايل الشركة · الأيام 15–19")}</p><div className="gc-section-title"><h2>{t("Your story.", "قصة شركتك.")}<br /><em>{t("In the same visual language.", "بالهوية نفسها.")}</em></h2><p>{t("Once the website is built, we present profile layout options using your approved identity. You choose a style, provide the remaining company data, then we produce the profile and align its approved information on the website.", "بعد تجهيز الموقع نعرض خيارات لتصميم البروفايل بهويتك المعتمدة. تختار الأسلوب وترسل بيانات الشركة المتبقية، ثم ننتج البروفايل ونوحّد معلوماته المعتمدة على الموقع.")}</p></div>
    <p className="gc-note">{t("Real cover previews from the sample collection. The layouts contain sample text; your final profile uses your approved identity and verified company information.", "لقطات فعلية لأغلفة من مجموعة النماذج. تتضمن التصاميم نصوصاً تجريبية؛ بروفايلك النهائي يُجهّز بهويتك المعتمدة وبيانات شركتك المدقّقة.")}</p>
    <div className="gc-gallery gc-real-profiles">{[
      ["1n4AqvNwXj5E7RVBwpyD-5TVILoicrd5P", t("01 / Black & white", "01 / أسود وأبيض"), t("A minimal cover with strong typography and contrasting interior layouts.", "غلاف بسيط بعناوين واضحة وصفحات داخلية متباينة.")],
      ["1tfIpggTCQ6zh70F2FuQ74GhKvv8y_UrM", t("02 / Corporate & structured", "02 / مؤسسي ومنظّم"), t("A clear company presentation with a visual contents page and service sections.", "عرض واضح للشركة مع فهرس بصري وتقسيمات للخدمات.")],
      ["1FDCTPQ7BI2xKFGjuEDc6n_xY0g7RWIQF", t("03 / Logistics & visual storytelling", "03 / لوجستيات وعرض بصري"), t("Dark backgrounds, logistics imagery and bold red accents.", "خلفيات غامقة وصور لوجستية ولمسات حمراء بارزة.")],
    ].map(([id,title,description],i)=><article key={id}><a className="gc-preview" href={`https://drive.google.com/file/d/${id}/view`} target="_blank" rel="noopener noreferrer"><img src={`/images/grow-case/profile-${i+1}.webp`} width="800" height="450" alt={title} loading="lazy" /></a><div className="gc-gallery-copy"><h3>{title}</h3><p>{description}</p><a className="gc-text-link" href={`https://drive.google.com/file/d/${id}/view`} target="_blank" rel="noopener noreferrer">{t("View the complete profile", "شاهد البروفايل كاملاً")} ↗</a></div></article>)}</div>
    <div className="gc-profile-collection"><span>{t("18 profile design references. Explore the full collection, then share the number of the style you prefer.", "18 نموذجاً مرجعياً لتصميم البروفايل. تصفّح المجموعة كاملة ثم شاركنا رقم النموذج الذي تفضّله.")}</span><a className="gc-button" href="https://drive.google.com/drive/folders/1U0TH5rRgJR-jfBZM4qidfUGyqnm7HliS" target="_blank" rel="noopener noreferrer">{t("Explore all profiles", "استعرض كل البروفايلات")} ↗</a></div>
    <div className="gc-io"><Block label={t("Your input · 2 working days", "مدخلاتك · يومان عمل")} text={t("Choose a layout and send company history, mission, services, team, verified project facts, credentials and publishable client references. We reuse the website content wherever suitable.", "اختر التصميم وأرسل تاريخ الشركة ورسالتها وخدماتها وفريقها وحقائق المشاريع والمؤهلات والمراجع المسموح بنشرها. نعيد استخدام محتوى الموقع حيث يلائم.")} /><Block label={t("MASAR output · 2 working days", "مخرجات مسار · يومان عمل")} text={t("A 10–12 page company profile and matching updates to the website. A typical flow covers introduction, story, vision, services, capabilities, projects, team and contact.", "بروفايل شركة من 10–12 صفحة، مع تحديثات متطابقة على الموقع. يشمل عادةً التعريف والقصة والرؤية والخدمات والقدرات والمشاريع والفريق والتواصل.")} /><Block label={t("Your approval", "اعتمادك")} text={t("Approve the layout and factual content, then review the finished profile and aligned website together for consistent names, figures and contact details.", "اعتمد الأسلوب والبيانات، ثم راجع البروفايل النهائي والموقع المحدّث معاً للتأكد من تطابق الأسماء والأرقام وبيانات التواصل.")} /></div>{gate(t("APPROVAL 03 — Company profile + website alignment. One approved source of company information across both.", "الاعتماد 03 — البروفايل + مواءمة الموقع. معلومات معتمدة وموحّدة عن الشركة في الاثنين."))}</div></section>
    <section className="gc-section gc-dark" id="handover"><div className="gc-wrap"><p className="gc-kicker">04 / {t("HANDOVER · DAYS 20–22", "التسليم · الأيام 20–22")}</p><div className="gc-section-title"><h2>{t("Beyond a website.", "أكثر من موقع.")}<br /><em>{t("Ready for daily business.", "جاهزية للعمل اليومي.")}</em></h2><p>{t("With the identity, website and profile approved, we finish the remaining Grow deliverables. You receive an organised package, a clear inventory and the access details needed to use it.", "بعد اعتماد الهوية والموقع والبروفايل نستكمل بقية مخرجات Grow. تستلم حزمة منظّمة وقائمة واضحة بالملفات وبيانات الوصول اللازمة لاستخدامها.")}</p></div><div className="gc-handover-grid"><article><span>01 / BRAND</span><h3>{t("Identity files", "ملفات الهوية")}</h3>{checklist([t("Approved logo in the agreed source and export formats", "الشعار المعتمد بصيغ المصدر والتصدير المتفق عليها"),t("Colour codes and typography references", "أكواد الألوان ومراجع الخطوط"),t("Mini brand guidelines · 5–8 pages", "دليل الهوية المختصر · 5–8 صفحات")])}</article><article><span>02 / DIGITAL</span><h3>{t("Digital presence", "الحضور الرقمي")}</h3>{checklist([t("Approved live corporate website", "موقع الشركة المنشور والمعتمد"),t("1-year hosting and up to 10 business emails", "استضافة سنة وما يصل إلى 10 عناوين بريد رسمي"),t("Email signature and LinkedIn branding", "توقيع البريد وتجهيز هوية لينكدإن")])}</article><article><span>03 / DOCUMENTS</span><h3>{t("Business documents", "مستندات الأعمال")}</h3>{checklist([t("Company profile · 10–12 pages", "بروفايل الشركة · 10–12 صفحة"),t("Quotation, invoice and PowerPoint designs", "تصميم عرض سعر وفاتورة وقالب باوربوينت"),t("Business card design", "تصميم بطاقة الأعمال")])}</article></div>
    <div className="gc-io"><Block label={t("Final inputs", "المدخلات النهائية")} text={t("Staff names and titles for cards, requested email addresses, authorised invoice details, domain access and LinkedIn page permissions where needed.", "أسماء الموظفين ومسمياتهم للبطاقات، عناوين البريد المطلوبة، بيانات الفاتورة المعتمدة، وصلاحيات النطاق وصفحة لينكدإن عند الحاجة.")} /><Block label={t("Release checks", "فحوصات التسليم")} text={t("Mobile and desktop layout, navigation and contact links, approved spelling and figures, profile download, email setup and completeness of the file inventory.", "عرض الموبايل والكمبيوتر، روابط التنقل والتواصل، صحة النصوص والأرقام المعتمدة، تحميل البروفايل، إعداد البريد واكتمال قائمة الملفات.")} /><Block label={t("Client acceptance", "استلامك واعتمادك")} text={t("Review one consolidated delivery list, approve the final version and receive access through an agreed secure channel. Hosting renewal and optional support are confirmed separately.", "راجع قائمة التسليم الموحّدة واعتمد النسخة النهائية واستلم بيانات الوصول بقناة آمنة متفق عليها. يُوضّح تجديد الاستضافة والدعم الاختياري بصورة مستقلة.")} /></div>{gate(t("APPROVAL 04 — Final acceptance, launch and handover. Your website, profile and business documents all follow the same identity.", "الاعتماد 04 — الاستلام النهائي والإطلاق والتسليم. موقعك وبروفايلك ومستنداتك تعمل بهوية واحدة."))}</div></section>
    <section className="gc-section gc-light" id="schedule"><div className="gc-wrap"><p className="gc-kicker">05 / {t("PROJECT CALENDAR", "تقويم المشروع")}</p><div className="gc-section-title"><h2>{t("Know the next step.", "اعرف الخطوة التالية.")}<br /><em>{t("And who owns it.", "ومَن المسؤول عنها.")}</em></h2><p>{t("A proposed 22-working-day sequence. Day 1 begins after scope and payment confirmation and receipt of the initial brief. Calendar dates and working days are agreed at kickoff.", "تسلسل مقترح من 22 يوم عمل. يبدأ اليوم الأول بعد تأكيد النطاق والدفع واستلام موجز الشركة. تُثبّت التواريخ وأيام العمل عند الانطلاق.")}</p></div><VisualTimeline ar={ar} rows={steps} /><div className="gc-schedule" role="region" tabIndex={0} aria-label={t("22 working day schedule", "برنامج 22 يوم عمل")}><table><thead><tr><th>{t("Day", "اليوم")}</th><th>{t("Stage", "المرحلة")}</th><th>{t("Owner", "المسؤول")}</th><th>{t("Milestone / output", "المطلوب / المخرج")}</th></tr></thead><tbody>{steps.map((s,i)=><tr key={s[0]} className={[2,5,8].includes(i)?"gc-client-row":""}><td><b>{s[0]}</b></td><td>{t(s[1],s[2])}</td><td><span className="gc-owner">{[2,5,8].includes(i)?t("Client", "العميل"):[0,3,11].includes(i)?t("Together", "معاً"):t("MASAR", "مسار")}</span></td><td>{t(s[3],s[4])}</td></tr>)}</tbody></table></div><div className="gc-timing-notes"><Block label={t("The schedule depends on approvals", "المواعيد مرتبطة بالاعتماد")} text={t("The plan assumes complete inputs and on-time approvals. Late content, additional revision rounds or changes to approved work move the dependent stages; we confirm a revised delivery date before continuing.", "تفترض الخطة اكتمال المدخلات والاعتمادات في وقتها. تأخر المحتوى أو جولات التعديل الإضافية أو تغيير عمل معتمد يؤجّل المراحل التابعة؛ نؤكد تاريخ التسليم المحدّث قبل المتابعة.")} /><Block label={t("Clear, consolidated feedback", "ملاحظات واضحة ومجمّعة")} text={t("Nominate one decision-maker. Send numbered comments with the model or page reference. Grow includes 3 logo revision rounds; their timing and the website/profile review scope are agreed at kickoff.", "حدّد مسؤول اعتماد واحداً، وأرسل ملاحظات مرقّمة مع اسم النموذج أو الصفحة. تشمل Grow ثلاث جولات تعديل للشعار؛ تُتفق مدتها ونطاق مراجعات الموقع والبروفايل عند الانطلاق.")} /></div></div></section>
    <section className="gc-section gc-content" id="content"><div className="gc-wrap"><p className="gc-kicker">{t("YOUR INPUT CHECKLIST", "قائمة مدخلاتك")}</p><div className="gc-section-title"><h2>{t("Prepare once.", "جهّز معلوماتك مرة.")}<br /><em>{t("Keep everything aligned.", "وحافظ على اتساقها.")}</em></h2><p>{t("Collect the core content in one document and the approved assets in one folder. We reuse verified information across your website, profile and business documents.", "اجمع المحتوى الأساسي في مستند واحد والمواد المعتمدة في مجلد واحد. نستخدم المعلومات المدققة نفسها في الموقع والبروفايل ومستندات الأعمال.")}</p></div><div className="gc-request"><pre>{requestText}</pre><div><button className="gc-button" type="button" onClick={async()=>{try{await navigator.clipboard.writeText(requestText);setCopied(true);}catch{setCopied(false);}}}>{copied?t("Copied ✓", "تم النسخ ✓"):t("Copy content checklist", "انسخ قائمة المحتوى")}</button><p aria-live="polite">{copied?t("Paste it into your document, complete it and share it through the agreed project channel.", "الصقها في مستندك، وأكمل البيانات ثم شاركها عبر قناة المشروع المتفق عليها."):t("You can also select and copy the checklist directly. Nothing is uploaded through this page.", "يمكنك أيضاً تحديد القائمة ونسخها مباشرة. لا تُرفع أي بيانات من خلال هذه الصفحة.")}</p></div></div><div className="gc-faq">{[
      [t("What if I need more time to choose?", "ماذا لو احتجت وقتاً أطول للاختيار؟"),t("Let us know before your review window ends. We update the dependent dates and agree a revised calendar. We do not treat silence as approval.", "أبلغنا قبل انتهاء مهلة المراجعة لنحدّث المواعيد التابعة ونتفق على التقويم الجديد. عدم الرد لا يُعتبر اعتماداً.")],
      [t("Can the identity change after website design starts?", "هل يمكن تعديل الهوية بعد بدء الموقع؟"),t("Yes, through a reviewed change request. We explain which website pages and documents need rework, then confirm any time or cost impact before proceeding.", "نعم، عبر طلب تغيير نراجعه معك. نوضح الصفحات والمستندات التي تحتاج إعادة عمل، ثم نؤكد أي أثر زمني أو مالي قبل التنفيذ.")],
      [t("Do I need to send the same content twice?", "هل أرسل المحتوى نفسه مرتين؟"),t("No. We reuse the approved website material for the profile and request only missing profile-specific facts. Any newly approved company information is then aligned on the website.", "لا. نعيد استخدام محتوى الموقع المعتمد ونطلب فقط المعلومات الإضافية الخاصة بالبروفايل. ثم نوحّد المعلومات الجديدة المعتمدة على الموقع.")],
      [t("Are the examples final projects or editable choices?", "هل النماذج مشاريع نهائية أم خيارات للاختيار؟"),t("They are reference design examples that explain the selection process. Your scope is one approved identity, one website and one company profile. Extra concepts or features are agreed separately.", "هي أمثلة تصميم مرجعية تشرح آلية الاختيار. نطاق مشروعك هوية واحدة وموقع واحد وبروفايل واحد معتمد. نتفق بصورة مستقلة على أي مفاهيم أو خصائص إضافية.")],
    ].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
  </>;
}
