import type { Metadata } from "next";
import HeaderBrand from "../header-brand";
import UKCompanyBadge from "../uk-company-badge";
import { packages } from "../commerce/catalog";
import GrowJourney from "./journey";
import "../footer-identity.css";
import "../yasser/yasser.css";
import "./grow-case.css";

type Props = { searchParams: Promise<Record<string, string | string[] | undefined>> };
export async function generateMetadata({ searchParams }: Props): Promise<Metadata> {
  const ar = (await searchParams).lang === "ar";
  return { title: ar ? "رحلة التصميم مع Grow | مسار" : "Grow Design Journey & Case Study | MASAR", description: ar ? "من اختيار الشعار والهوية إلى الموقع والبروفايل والتسليم. رحلة باقة Grow مع نماذج فعلية ومدخلات ومخرجات وبرنامج زمني واضح." : "Explore the Grow client journey: brand concepts, website directions, content, company profile and handover, with real examples and a clear working-day schedule.", alternates: { canonical: "https://masarps.com/grow-case", languages: { ar: "https://masarps.com/grow-case?lang=ar", en: "https://masarps.com/grow-case?lang=en" } } };
}
export default async function GrowCase({ searchParams }: Props) {
  const ar = (await searchParams).lang === "ar";
  const lang = ar ? "ar" : "en";
  const t = (en: string, arabic: string) => ar ? arabic : en;
  const grow = packages.find(p => p.id === "grow")!;
  return <main className={`cx-page theme-masar yp-page gc-page ${lang}`} dir={ar ? "rtl" : "ltr"}>
    <section className="cx-hero gc-site-header"><header><HeaderBrand href={`/?lang=${lang}`} /><nav aria-label={t("Main navigation", "التنقل الرئيسي")}>
      {[["about", t("About Masar", "عن مسار")],["services",t("Services", "الخدمات")],["method",t("Method", "المنهجية")],["faq",t("FAQ", "الأسئلة الشائعة")]].map(([id,label])=><a key={id} href={`/?lang=${lang}#${id}`}>{label}</a>)}
      <span className="nav-package-wrap"><a className="nav-packages" href={`/?lang=${lang}#services`}>{t("Packages & Pricing", "الباقات والأسعار")}</a><span className="nav-package-menu">{[["/services/procurement",t("Procurement, Strategic Sourcing & Vendor Management", "المشتريات والتوريد الاستراتيجي وإدارة الموردين")],["/services/business-setup",t("Business, Investment & Development Advisory", "استشارات الأعمال والاستثمار والتطوير")],["/services/commercial-contracts",t("Commercial & Contracts Advisory", "الاستشارات التجارية والتعاقدية")],["/packages",t("Brand Identity & Market Presence", "الهوية والحضور في السوق")]].map(([path,label])=><a key={path} href={`${path}?lang=${lang}`}>{label}</a>)}</span></span></nav><div className="cx-actions"><a className="gc-lang-link" aria-label={ar ? "Switch to English" : "التبديل إلى العربية"} href={`/grow-case?lang=${ar ? "en" : "ar"}`}>{ar ? "EN" : "AR"} ◉</a><a className="contact-chip" href={`/?lang=${lang}#contact`}>{t("Contact", "تواصل معنا")} ✉</a></div></header></section>
    <section className="yp-hero gc-hero" id="overview">

      <div className="gc-hero-content"><div><p className="gc-kicker">GROW / {t("THE CLIENT JOURNEY", "رحلة العميل")}</p><h1>{t("Your identity.", "هويتك.")}<br />{t("Your website.", "موقعك.")}<br /><em>{t("One clear journey.", "رحلة واضحة.")}</em></h1><p className="gc-hero-description">{t("From the first logo concept to a complete business presence. See what happens, what you choose and what you receive—at every step.", "من أول فكرة للشعار إلى حضور متكامل لشركتك. اعرف ماذا نصمم، ومتى تختار، وماذا تستلم في كل خطوة.")}</p><div className="gc-actions"><a className="gc-button" href="#identity">{t("Explore the journey", "اكتشف رحلة التصميم")} ↓</a><a className="gc-text-link" href="#schedule">{t("View the timeline", "شاهد البرنامج الزمني")} ↗</a></div></div><aside className="gc-hero-summary"><span className="gc-kicker">{t("ILLUSTRATIVE CASE STUDY", "دراسة تطبيقية توضيحية")}</span><h2>SAC<br /><em>Logistics.</em></h2><p>{t("Real design examples show how choices come together. A walkthrough of the process, with no assumed final client selection or performance claims.", "نماذج تصميم فعلية توضّح كيف تتكامل اختياراتك، لشرح آلية العمل دون افتراض اعتماد نهائي من العميل أو نتائج تجارية للمشروع.")}</p><div className="gc-summary-stats"><div><strong>03</strong><span>{t("Website directions", "توجهات للموقع")}</span></div><div><strong>22</strong><span>{t("Working days · proposed", "يوم عمل · مقترح")}</span></div></div><a href={`/packages?lang=${lang}`}>GROW · {grow.sar.toLocaleString("en-US")} {t("SAR", "ر.س")} ↗</a></aside></div>
      <div className="gc-hero-bottom"><span>MASAR · BRAND & DIGITAL</span><span>{t("Identity → Website → Profile → Handover", "الهوية ← الموقع ← البروفايل ← التسليم")}</span></div>
    </section>
    <GrowJourney ar={ar} />
    <section className="gc-section gc-light" id="scope"><div className="gc-wrap"><p className="gc-kicker">{t("THE COMPLETE GROW PACKAGE", "باقة GROW المتكاملة")}</p><div className="gc-section-title"><h2>{t("Everything follows", "كل التفاصيل تنطلق")}<br /><em>{t("one identity.", "من هوية واحدة.")}</em></h2><p>{t("Your approved logo, colours and typography become the foundation for every digital page and business document.", "الشعار والألوان والخطوط التي تعتمدها تصبح المرجع لكل صفحة رقمية ومستند يعكس شركتك.")}</p></div><div className="gc-scope-list">{grow.features?.map(([en, arabic], i) => <div key={en}><span>{String(i + 1).padStart(2,"0")}</span><p>{t(en, arabic)}</p></div>)}</div><p className="gc-note">{t("100% upfront after scope confirmation. Website pages, languages, revision scope and delivery formats are agreed before kickoff. Procurement tools and a CMS are separate package options.", "الدفع 100% مقدماً بعد تأكيد النطاق. نتفق قبل البدء على صفحات الموقع ولغاته وجولات المراجعة وصيغ التسليم. أدوات المشتريات ولوحة إدارة المحتوى خيارات ضمن باقات أخرى.")}</p></div></section>
    <section className="gc-end" id="start"><div className="gc-wrap"><p className="gc-kicker">{t("READY WHEN YOU ARE", "خطوتك الأولى")}</p><h2>{t("A clear beginning.", "بداية واضحة.")}<br /><em>{t("A complete presence.", "وحضور متكامل.")}</em></h2><p>{t("Choose Grow, share your business brief and nominate one person to approve each stage. We will confirm your scope and project calendar before we begin.", "اختر Grow، وأرسل نبذة عن شركتك وحدد شخصاً واحداً للاعتمادات. نؤكد معك النطاق وتقويم المشروع قبل الانطلاق.")}</p><div className="gc-actions"><a className="gc-button" href={`/packages?lang=${lang}`}>{t("Explore Grow", "استعرض باقة Grow")} ↗</a><a className="gc-text-link" href="mailto:info@masarps.com?subject=Grow%20project%20brief">{t("Discuss your project", "ناقش مشروعك معنا")} ↗</a></div></div></section>
    <footer className="masar-footer"><div className="footer-brand"><a className="cx-logo" href={`/?lang=${lang}#top`} aria-label={ar ? "مسار — الصفحة الرئيسية" : "Masar home"}><span className="logo-word"><b>MASAR</b><small>PROCUREMENT / SOLUTIONS</small></span></a><UKCompanyBadge /></div><div className="footer-company"><p>{t("Smart procurement solutions connecting markets and building resilient supply chains.", "حلول مشتريات ذكية تربط الأسواق وتبني سلاسل إمداد أكثر مرونة.")}</p><address><strong>{t("Registered Office Address", "عنوان المكتب المسجّل")}</strong><span dir="ltr">71-75, Shelton Street, Covent Garden<br />London, WC2H 9JQ, United Kingdom</span></address></div><div className="footer-bottom"><i className="footer-light" aria-hidden="true" /><a href="mailto:info@masarps.com">info@masarps.com</a><a href="tel:+966505476689">+966 50 547 6689</a><span>© 2026 MASAR. {t("All rights reserved.", "جميع الحقوق محفوظة.")}</span></div></footer>
  </main>;
}
